services:
  # Frontend React App
  - type: web
    name: sunobot-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    domains:
      - sunobot.com
      - www.sunobot.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://api.sunobot.com

  # Backend Django API
  - type: web
    name: sunobot-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT
    domains:
      - api.sunobot.com
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DEBUG
        value: "0"
      - key: ALLOWED_HOSTS
        value: api.sunobot.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://sunobot.com
      - key: DATABASE_URL
        fromDatabase:
          name: sunobot-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: REDIS_URL
        fromService:
          type: redis
          name: sunobot-redis
          property: connectionString

  # Redis instance
  - type: redis
    name: sunobot-redis
    ipAllowList: []
    plan: free

databases:
  - name: sunobot-db
    databaseName: sunobot
    user: sunobot
    plan: free 