services:
  # Frontend React App
  - type: static
    name: sunobot-frontend
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://sunobot-backend.onrender.com

  # Backend Django API
  - type: web
    name: sunobot-backend
    env: python
    plan: free
    buildCommand: apt-get update && apt-get install -y ffmpeg python3-magic && pip install --no-cache-dir -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn darwix_ai.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DEBUG
        value: "0"
      - key: ALLOWED_HOSTS
        value: sunobot-backend.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://sunobot-frontend.onrender.com
      - key: SECRET_KEY
        generateValue: true
      - key: HF_TOKEN
        sync: false  # You'll need to set this manually in Render dashboard

  # Redis instance
  - type: redis
    name: sunobot-redis
    ipAllowList: []
    plan: free

databases:
  - name: sunobot-db
    databaseName: sunobot
    user: sunobot
    plan: free 