services:
  # Frontend React App
  - type: static
    name: sunobot-frontend
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://sunobot-backend.onrender.com

  # Backend Django API
  - type: web
    name: sunobot-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DEBUG
        value: "0"
      - key: ALLOWED_HOSTS
        value: sunobot-backend.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://sunobot-frontend.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: sunobot-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true

  # Use SQLite instead of PostgreSQL for free tier
  - type: web
    name: sunobot-db
    env: python
    plan: free
    buildCommand: echo "Using SQLite database"
    startCommand: echo "Database ready"

  # Redis instance
  - type: redis
    name: sunobot-redis
    ipAllowList: []
    plan: free

databases:
  - name: sunobot-db
    databaseName: sunobot
    user: sunobot
    plan: free 