services:
  # Frontend React App
  - type: web
    name: darwix-ai-frontend
    env: node
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: serve -s dist
    envVars:
      - key: VITE_API_URL
        value: https://darwix-ai.onrender.com
    autoDeploy: true
    plan: free

  # Backend Django API
  - type: web
    name: darwix-ai
    env: docker
    dockerfilePath: ./Dockerfile
    dockerCommand: |
      docker build -t darwix-ai .
      docker run -p 8000:8000 darwix-ai
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        value: django-insecure-8$%^&*()_+qwertyuiopasdfghjklzxcvbnm,./;'[]\=-0987654321
      - key: ALLOWED_HOSTS
        value: "*"
      - key: CORS_ALLOWED_ORIGINS
        value: "*"
      - key: DATABASE_URL
        fromDatabase:
          name: darwix-db
          property: connectionString
    healthCheckPath: /health/
    autoDeploy: true
    plan: free

  # Redis instance
  - type: redis
    name: sunobot-redis
    ipAllowList: []
    plan: free

databases:
  - name: darwix-db
    databaseName: darwix
    user: darwix
    plan: free 